version: '3.8'

services:
  geotech-ai:
    build: .
    container_name: geotech-ai-service
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - ENVIRONMENT=production
    env_file:
      - .env
    volumes:
      - "./logs:/app/logs"      # Persistent observability logs
      - "./data:/app/data"
    depends_on:
      - qdrant
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  qdrant:
    image: qdrant/qdrant:v1.14.1
    container_name: geotech-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:

networks:
  default:
    name: geotech-network